version: '3.8'
services:
  front:
    container_name: staging
    image: docker-staging:latest
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=development
    ports:
      - 80:3000
