name: Build, Test, and Deploy (Development)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on:
      labels: front-staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          docker compose down
          docker compose -f "docker-compose.prod.yml" up -d --build
